### ISSUE TITLE
NS Api to change

### ISSUE THREAD

**Issue by hmmbob** [aquatix/ns-api#16]
Yesterday I received an email that NS is to upgrade their API and the current API will be phased out on October 1st. I wanted to make sure you are aware, and see if this implicates that some changes need to be made to this package, which is used in Home Assistant as well.

Text of the email:

> Beste NS-API gebruiker,
> 
> U ontvangt deze e-mail omdat u met dit e-mailadres geregistreerd staat als gebruiker van de NS-API.
> 
> De NS-API zoals u die kent zal uitgefaseerd worden. Van u als gebruiker verwachten wij, als u gebruik wilt blijven maken van onze services, dat u gaat migreren naar onze nieuwe API.
> 
> Hoe u dit aan moet pakken is te lezen in de migratiehandleiding die we met deze mail meesturen.
>  
> 
> Kort samengevat gaat het volgende voor u veranderen:
> ·         U heeft voor het gebruik van de nieuwe API een API-key nodig. Deze is aan te vragen via het NS API portaal
> ·         URL’s naar de services veranderen
> ·         Het response is in het JSON formaat
> ·         De veldnamen van de parameters en de responses zijn verandert.
> 
> U krijgt 6 maanden de tijd om de migratie uit te voeren. De planning is om per 1 oktober 2019 de oude API uit te schakelen en onze services niet meer beschikbaar te stellen.
> 
> Bij vragen kunt u ons bereiken via het volgende e-mailadres: nsr.api@ns.nl
> 
> Met vriendelijke groet,
> 
> NS API team

I have added the attached file to this issue as well.
[NS REST API migration guide.pdf](https://github.com/aquatix/ns-api/files/3022203/NS.REST.API.migration.guide.pdf)

**Comment by aquatix** [comment]
Yesterday I got the same mail (I think they even announced it a while ago already). I was pondering whether I wanted to do the rewrite, as of the start of this year I don't use the train as often as I used to.

However, I still have a use for it, and I'm pleasantly surprised to find it being used in Home Assistant as well, so I'll certainly look into the new specs.

Yesterday not much information was available yet, I'll look into it this weekend (together with requesting a new account at the NS API portal).

I'll post back here when I have a better idea what work it involves :)

**Comment by hmmbob** [comment]
Cool. I'm not using it too much either, since I switched jobs. But I do know that there are quite a few users.

This is the Home Assistant integration:
https://www.home-assistant.io/components/sensor.nederlandse_spoorwegen/
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/nederlandse_spoorwegen/sensor.py

**Comment by aquatix** [comment]
I also found your blogpost on Tweakers, nice. Thanks for the pointers, I'll definitely will look into updating the library.
Also, as someone wanting to use HA a bit more in the near-ish future, I'm kind of invested ;)

**Comment by b10m** [comment]
I'll await your updates and see if the home assistant module needs patching.

**Comment by xatr0z** [comment]
Just to be sure: For new users like me, it isn't possible to use nsapi right now. Registrations to the old API are already closed

**Comment by aquatix** [comment]
@xatr0z ah, that's annoying :( I'm really busy at work, so my energy when at home isn't always hobby-grade, but I'm working on this.

**Comment by Squixx** [comment]
https://github.com/aquatix/ns-api/pull/17

**Comment by janjbrand** [comment]
What's the current status? When can we expect this change in the Home Assistant integration?

**Comment by kevintuhumury** [comment]
@aquatix Wondering the same thing @janjbrand is asking about. We're past the 1st of October, so I'm guessing the old API is deprecated now. As a new user (don't have credentials to the old API), I haven't been able to use the Home Assistant integration, which uses this library, for months now. Would be nice to have the update in Home Assistant so that it can actually be used again.

Don't want to be that guy, but if this isn't maintained anymore, maybe @Squixx should release a version so it can be integrated into Home Assistant again.

**Comment by kevintuhumury** [comment]
So, is there any progress on this? It's been over 2 months already since the PR (#17) has been made. I love that you've made this and that it is included in Home Assistant through an integration, but this issue has been here since March. What if there's another issue. Is that going to take another year to be updated?

@aquatix and @Squixx could you please look at getting this merged?

If not, I'm actually thinking of just forking this repository and merging in #17 into that and creating a PR for Home Assistant to use the forked repository as so many people want to use this functionality.

**Comment by aquatix** [comment]
@kevintuhumury I appreciate the way you talk about this. I've seen developers of projects I use disappear in the past because of work, home situation and such, and now I'm suddenly one myself. It does not sit well with me :)

Anyway, I think there are a few options from here:

- @Squixx can do the new PR without the line-ending changes (and the Microsoft-copyrighted docker source file). This would be my preference, as he would be in the history with his work in the way Git intends
- I can take the PR by @Squixx and apply the changes anew on a new branch, without the above mentioned changes, and commit them myself, with of course a honourable mention to @Squixx for their hard work
- I can apply the PR wholesale, losing al history because of the line ending changes in all source files. This would be regrettable, and does not have my preference, but it would not be lethal.

I would very much like @Squixx to chime in on my comments on the code. I'll be preparing a PR for option 2 in the meanwhile just in case (and to better see what changed).

**Comment by b10m** [comment]
Any update on this @aquatix ?

**Comment by janjbrand** [comment]
Any news?

**Comment by aquatix** [comment]
Thanks everyone on your patience with this. I'm currently working on the PR mentioned above and will be committing shortly.

**Comment by aquatix** [comment]
Well, here you go: https://pypi.org/project/nsapi/ :)

**Comment by aquatix** [comment]
@YarmoM did some great work getting the changes in Home Assistant. https://github.com/home-assistant/home-assistant/pull/30971 will bring it further up to date. Hopefully it gets included in the next version of HA :)

**Comment by Squixx** [comment]
Sorry, had a busy couple of months at work, so haven't been tracking github. Thanks for fixing my pr and merging this!
